import {
  BAlert,
  BAspect,
  BAvatar, BAvatarGroup,
  BBadge,
  BBreadcrumb, BBreadcrumbItem, BBreadcrumbLink,
  BButtonGroup,
  BButtonToolbar,
  BBtn,
  BButton,
  BCalendar,
  BButtonClose,
  BCard,
  BCardHeader,
  BCardBody,
  BCardTitle,
  BCardSubTitle,
  BCardFooter,
  BCardImg,
  BCardImgLazy,
  BCardText,
  BCardGroup,
  BCarousel,
  BCarouselSlide,
  BCollapse,
  BDropdown,
  BDropdownItem,
  BDropdownItemButton,
  BDropdownHeader,
  BDropdownDivider,
  BDropdownForm,
  BDropdownText,
  BDropdownGroup,
  BEmbed,
  BFormCheckbox,
  BFormCheckboxGroup,
  BFormDatepicker,
  BFormFile,
  BFormGroup,
  BFormInput,
  BFormRadio, BFormRadioGroup,
  BFormRating,
  BFormSelect, BFormSelectOption, BFormSelectOptionGroup,
  BFormSpinbutton,
  BFormTags, BFormTag,
  BFormTextarea,
  BFormTimepicker,
  BForm, BFormDatalist, BFormText, BFormInvalidFeedback, BFormValidFeedback,
  BImg, BImgLazy,
  BInputGroup,
  BInputGroupAddon,
  BInputGroupPrepend,
  BInputGroupAppend,
  BInputGroupText,
  BJumbotron,
  BContainer, BRow, BCol, BFormRow,
  BLink,
  BListGroup, BListGroupItem,
  BMedia, BMediaAside, BMediaBody,
  BModal,
  VBModal,
  BNav, BNavItem, BNavText, BNavForm, BNavItemDropdown,
  BNavbar, BNavbarNav, BNavbarBrand, BNavbarToggle,
  BOverlay,
  BPaginationNav,
  BPagination,
  BPopover,
  BProgress,
  BProgressBar,
  BSidebar,
  BSkeleton, BSkeletonIcon, BSkeletonImg, BSkeletonTable, BSkeletonWrapper,
  BSpinner,
  BTable,
  BTableLite,
  BTableSimple,
  // Helper components
  BTbody,
  BThead,
  BTfoot,
  BTr,
  BTd,
  BTh,
  BTabs,
  BTab,
  BTime,
  BToast, BToaster,
  BTooltip
} from 'bootstrap-vue'
let importBootstrap = {}
let directiveBootstraps = {}
function bootstrapImports () {
  importBootstrap = {
    BAlert,
    BAspect,
    BAvatar,
    BAvatarGroup,
    BBadge,
    BBreadcrumb,
    BBreadcrumbItem,
    BBreadcrumbLink,
    BButtonGroup,
    BBtnGroup: BButtonGroup,
    BButtonToolbar,
    BBtnToolbar: BButtonToolbar,
    BButton,
    BBtn: BButton,
    BButtonClose,
    BBtnClose: BButtonClose,
    BCalendar,
    BCard,
    BCardHeader,
    BCardBody,
    BCardTitle,
    BCardSubTitle,
    BCardFooter,
    BCardImg,
    BCardImgLazy,
    BCardText,
    BCardGroup,
    BCarousel,
    BCarouselSlide,
    BCollapse,
    BDropdown,
    BDd: BDropdown,
    BDropdownItem,
    BDdItem: BDropdownItem,
    BDropdownItemButton,
    BDropdownItemBtn: BDropdownItemButton,
    BDdItemButton: BDropdownItemButton,
    BDdItemBtn: BDropdownItemButton,
    BDropdownHeader,
    BDdHeader: BDropdownHeader,
    BDropdownDivider,
    BDdDivider: BDropdownDivider,
    BDropdownForm,
    BDdForm: BDropdownForm,
    BDropdownText,
    BDdText: BDropdownText,
    BDropdownGroup,
    BDdGroup: BDropdownGroup,
    BEmbed,
    BFormCheckbox,
    BCheckbox: BFormCheckbox,
    BCheck: BFormCheckbox,
    BFormCheckboxGroup,
    BCheckboxGroup: BFormCheckboxGroup,
    BCheckGroup: BFormCheckboxGroup,
    BFormDatepicker,
    BDatepicker: BFormDatepicker,
    BFormFile,
    BFile: BFormFile,
    BFormGroup,
    BFormInput,
    BFormRadio,
    BRadio: BFormRadio,
    BFormRadioGroup,
    BRadioGroup: BFormRadioGroup,
    BFormRating,
    BRating: BFormRating,
    BFormSelect,
    BFormSelectOption,
    BFormSelectOptionGroup,
    BSelect: BFormSelect,
    BSelectOption: BFormSelectOption,
    BSelectOptionGroup: BFormSelectOptionGroup,
    BFormSpinbutton,
    BSpinbutton: BFormSpinbutton,
    BFormTags,
    BTags: BFormTags,
    BFormTag,
    BTag: BFormTag,
    BFormTextarea,
    BTextarea: BFormTextarea,
    BFormTimepicker,
    BTimepicker: BFormTimepicker,
    BForm,
    BFormDatalist,
    BDatalist: BFormDatalist,
    BFormText,
    BFormInvalidFeedback,
    BFormFeedback: BFormInvalidFeedback,
    BFormValidFeedback,
    // Added here for convenience
    BImg,
    BImgLazy,
    BInputGroup,
    BInputGroupAddon,
    BInputGroupPrepend,
    BInputGroupAppend,
    BInputGroupText,
    BJumbotron,
    BContainer,
    BRow,
    BCol,
    BFormRow,
    BLink,
    BListGroup,
    BListGroupItem,
    BMedia,
    BMediaAside,
    BMediaBody,
    BModal,
    BNav,
    BNavItem,
    BNavText,
    BNavForm,
    BNavItemDropdown,
    BNavItemDd: BNavItemDropdown,
    BNavDropdown: BNavItemDropdown,
    BNavDd: BNavItemDropdown,
    BNavbar,
    BNavbarNav,
    BNavbarBrand,
    BNavbarToggle,
    BNavToggle: BNavbarToggle,
    BOverlay,
    BPaginationNav,
    BPagination,
    BPopover,
    BProgress,
    BProgressBar,
    BSidebar,
    BSkeleton,
    BSkeletonIcon,
    BSkeletonImg,
    BSkeletonTable,
    BSkeletonWrapper,
    BSpinner,
    BTableSimple,
    BTbody,
    BThead,
    BTfoot,
    BTr,
    BTd,
    BTh,
    BTable,
    BTableLite,
    BTabs,
    BTab,
    BTime,
    BToast,
    BToaster,
    BTooltip
  }
  directiveBootstraps = {
    VBModal
  }
}

export { importBootstrap, bootstrapImports }
